# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b2184a60f404b1dc3f17622c0981e4eddcce58e57b28d3c163a7bc06c621976c7e9e0161a6121786656251a4671a184bf3a764e920469de9c10315beba996e5

test:
  secret_key_base: 41e1c1510d8c8371ae05924c45704d6f0bc130f1ccd6c56d5304afdd2e3848cfab5588afbe420c37d78b5f213fdac46b810694c1c73df887ecbc2998a3cadf3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
